name-template: 'Meshery Operator v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'kind/feature'
      - 'kind/enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'kind/fix'
      - 'kind/bugfix'
      - 'kind/bug'
  - title: '🧰 Maintenance'
    label: 'kind/chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## What's New
  $CHANGES
  
  ## Contributors
  
  Thank you to our contributors for making this release possible:
  $CONTRIBUTORS
