version: "2"

linters:
  enable:
    - goconst
    - gocritic
    - govet
    - staticcheck
    - unused
    - cyclop
  
  exclusions:
    paths:
      - vendor
      - bundle
      - config
      - hack
      - helpers
      - img
  
  settings:
    goconst:
      min-len: 3
      min-occurrences: 3
    
    govet:
      enable-all: true
    
    staticcheck:
      checks: ["all", "-ST1005"]
    
    unused:
      exported-fields-are-used: false
    
    cyclop:
      max-complexity: 15

formatters:
  enable:
    - gci
    - gofmt
    - goimports
  
  settings:
    gci:
      sections:
        - standard
        - default
    
    gofmt:
      simplify: true

run:
  timeout: 5m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
