apiVersion: v1
kind: Service
metadata:
  labels:
    app: meshery
    component: operator
  name: operator-metrics-service
  namespace: meshery
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app: meshery
    component: operator
