namePrefix: meshery-
namespace: meshery
resources:
- role.yaml
- role_binding.yaml
- controller_role.yaml
- controller_role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- metrics_reader_role.yaml
