namePrefix: meshery-
namespace: meshery
resources:
  - role.yaml
  - role_binding.yaml
  - controller_role.yaml
  - controller_role_binding.yaml
  - leader_election_role.yaml
  - leader_election_role_binding.yaml
  - metrics_reader_role.yaml # Renamed and moved - This role is needed for metrics scraping

# The following resources were related to the deprecated kube-rbac-proxy sidecar and have been removed:
# - auth_proxy_service.yaml
# - auth_proxy_role.yaml
# - auth_proxy_role_binding.yaml
# - auth_proxy_client_clusterrole.yaml (renamed to metrics_reader_role.yaml above)

# --- Additions needed for built-in auth ---
# You still need to add bindings for the metrics_reader_role (e.g., for Prometheus)
# and ensure controller_role.yaml has tokenreviews/subjectaccessreviews permissions.
