apiVersion: meshery.layer5.io/v1alpha1
kind: Broker
metadata:
  name: meshery-broker
  namespace: meshery
  labels:
    app: meshery
    component: controller
    version: v0.1.15
  annotations:
    meshery/component-type: management-plane
spec:
  size: 1
