name: Meshery-Operator Build and Releaser
permissions: read-all

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  docker:
    name: Docker build and push
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 1
      - name: Docker login
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker edge build & tag
        if: startsWith(github.ref, 'refs/tags/') != true && success()
        run: |
          DOCKER_BUILDKIT=1 docker build --no-cache -t ${{ secrets.IMAGE_NAME }}:edge-latest .
          docker tag ${{ secrets.IMAGE_NAME }}:edge-latest ${{ secrets.IMAGE_NAME }}:edge-${GITHUB_SHA::7}
      - name: Docker edge push
        if: startsWith(github.ref, 'refs/tags/') != true && success()
        run: |
          docker push ${{ secrets.IMAGE_NAME }}:edge-latest
          docker push ${{ secrets.IMAGE_NAME }}:edge-${GITHUB_SHA::7}
      - name: Docker stable build & tag
        if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') && success()
        run: |
          DOCKER_BUILDKIT=1 docker build --no-cache -t ${{ secrets.IMAGE_NAME }}:stable-latest .
          docker tag ${{ secrets.IMAGE_NAME }}:stable-latest ${{ secrets.IMAGE_NAME }}:stable-${GITHUB_REF/refs\/tags\//}
          docker tag ${{ secrets.IMAGE_NAME }}:stable-latest ${{ secrets.IMAGE_NAME }}:stable-${GITHUB_SHA::7}
      - name: Docker stable push
        if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') && success()
        run: |
          docker push ${{ secrets.IMAGE_NAME }}:stable-latest
          docker push ${{ secrets.IMAGE_NAME }}:stable-${GITHUB_REF/refs\/tags\//}
          docker push ${{ secrets.IMAGE_NAME }}:stable-${GITHUB_SHA::7}
#       - name: Docker Hub Description
#         if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') && success()
#         uses: peter-evans/dockerhub-description@v2.0.0
#         env:
#           DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#           DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#           DOCKERHUB_REPOSITORY: ${{ secrets.IMAGE_NAME }}
