name: Integration Tests
permissions: read-all

on:
  push:
    branches:
      - "master"
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "Makefile"
      - "config/**"
      - "integration-tests/**"
      - ".github/workflows/integration-tests-ci.yml"
  pull_request:
    branches:
      - "master"
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "Makefile"
      - "config/**"
      - "integration-tests/**"
      - ".github/workflows/integration-tests-ci.yml"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "info"

jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3
        with:
          fetch-depth: 2
      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: go.mod
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0 
      - name: Install Kind and kubectl
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
      - name: Check integration tests dependencies
        run: make integration-tests-check-dependencies
      - name: Integration tests set up
        run: make integration-tests-setup
      - name: Integration tests set up - print debug output
        run: |
          make integration-tests-setup-debug-output
          echo "Integration tests setup failed - stopping workflow"
          exit 1
        if: failure()
      - name: Integration tests run
        run: make integration-tests-run
      - name: Integration tests clean up
        run: make integration-tests-cleanup
        if: always()
      - name: Upload integration test logs (if any)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: operator-logs
          path: integration-tests/*.log
          if-no-files-found: warn
